spring:
  application:
    name: ergonomics-monitor
  threads:
    virtual:
      enabled: true
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/ergonomics_db
    username: postgres
    password: password
  ai:
    ollama:
      base-url: http://localhost:11434
      chat:
        model: llama3 # lub inny model, kt√≥ry masz pobrany w Ollama
